services:
  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend_net

  backend:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port ${APP_PORT}
      --reload
    depends_on:
      - redis
    networks:
      - shared_net
      - backend_net
      - proxy
    volumes:
      - ./backend:/app
      - shared_tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automation-backend.rule=Host(`${BACKEND_BASE_URL}`)"
      - "traefik.http.routers.automation-backend.entrypoints=websecure"
      - "traefik.http.routers.automation-backend.tls=true"
      - "traefik.http.routers.automation-backend.tls.certresolver=le"
      - "traefik.http.services.automation-backend.loadbalancer.server.port=${APP_PORT}"

  worker:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    user: "${UID}:${GID}"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: >
      watchmedo auto-restart
      --directory=./
      --pattern="*.py"
      --recursive --
      celery -A app.celery_app worker
      --loglevel=info
      --concurrency=2
    depends_on:
      - redis
    networks:
      - backend_net
      - shared_net
    volumes:
      - ./backend:/app
      - shared_tmp:/tmp

  # flower:
  #   image: mher/flower
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   command: >
  #     celery --broker=${CELERY_BROKER_URL} flower --port=5555
  #   depends_on:
  #     - worker
  #   networks:
  #     - backend_net
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.automation-flower.rule=Host(`${FLOWER_URL}`)"
  #     - "traefik.http.routers.automation-flower.entrypoints=websecure"
  #     - "traefik.http.routers.automation-flower.tls=true"
  #     - "traefik.http.routers.automation-flower.tls.certresolver=le"
  #     - "traefik.http.services.automation-flower.loadbalancer.server.port=${FLOWER_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automation-frontend.rule=Host(`${PUBLIC_URL}`)"
      - "traefik.http.routers.automation-frontend.entrypoints=websecure"
      - "traefik.http.routers.automation-frontend.tls=true"
      - "traefik.http.routers.automation-frontend.tls.certresolver=le"

networks:
  shared_net:
    external: true
  proxy:
    external: true
  backend_net:

volumes:
  shared_tmp:
