services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: >
      sh -c '
      if [ "$PRODUCTION" = "false" ]; then
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT} --reload;
      else
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT};
      fi'
    networks:
      - shared_net
      - backend_net
    volumes:
      - ./backend:/app
      - ./browser_profiles:/browser_profiles
      - shared_tmp:/tmp

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c '
      if [ "$PRODUCTION" = "false" ]; then
        watchmedo auto-restart --directory=./ --pattern="*.py" --recursive -- \
          celery -A app.celery_app worker --loglevel=info --concurrency=2;
      else
        celery -A app.celery_app worker --loglevel=info --concurrency=2;
      fi'
    depends_on:
      - redis
    networks:
      - shared_net
      - backend_net
    volumes:
      - ./backend:/app
      - ./browser_profiles:/browser_profiles
      - shared_tmp:/tmp

  flower:
    image: mher/flower
    env_file:
      - .env
    restart: unless-stopped
    command: >
      celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      - worker
    networks:
      - backend_net

  redis:
    image: redis:latest
    networks:
      - backend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - shared_net

networks:
  shared_net:
    external: true
  backend_net:

volumes:
  shared_tmp:
