services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: >
      sh -c '
      if [ "$PRODUCTION" = "false" ]; then
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT} --reload;
      else
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT};
      fi'
    networks:
      - shared_net
    volumes:
      - ./backend:/app

  # redis:
  #   image: redis:7-alpine
  #   networks:
  #     - shared_net
  #
  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   command:
  #     [
  #       "celery",
  #       "-A",
  #       "app.worker.celery_app",
  #       "worker",
  #       "--loglevel=info",
  #       "--concurrency=1",
  #     ]
  #   depends_on:
  #     - redis
  #   networks:
  #     - shared_net
  #   volumes:
  #     - ./backend:/app
  #     - shared_tmp:/tmp
  #
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: ["npm", "run", "dev"]
  #   depends_on:
  #     - backend

networks:
  shared_net:
    external: true
